#!/bin/bash
  1
  2 START
  3 I will be there for you my little boy
  4 so dont panic as they always say put who belive in thet facts exept you some     time you find your self okay i am at the end of the line
  5 so lets tray my tric
  6
  7 dos that work?1
